"""
Django settings for riwaz project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_74nhp_=h9cs=*hdlz+9rdf!hi9)1yz^)p^c2baghro^o5#n63'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    'jet',
    'jet.dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'riwaz.users',
    'sellers',
    'vip_admin',
    'riwaz.categories',
    'riwaz.category_tag',
    'riwaz.category_numbers',
    'riwaz.number',
    'riwaz.paytm',
    'riwaz.subscribers',
    'riwaz.homeimages',
    'tagconstants',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'riwaz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'riwaz.wsgi.application'

# Constants
TAG_CONSTANTS = {
    'PROJECT_NAME': 'vipnumbersshop.com',
    'COMPANY_NAME': 'VIP Number Shop',
    'PROJECT_URL': 'https://www.vipnumbershop.com/',
}

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'numbers_shop_vip',
        'USER': 'root',
        'PASSWORD': 'vip@number@mysql@123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    # '/var/www/html/p_project/pureloan/static/',
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC = os.path.join(BASE_DIR, 'static')
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True
JET_DEFAULT_THEME = 'default'

# SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.vipnumbershop.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'vipnumber70091@gmail.com'
# DEFAULT_FROM_EMAIL = 'vipnumber70091@gmail.com'
# EMAIL_HOST_PASSWORD = 'vipnumber1234'

# SMTP
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'email-smtp.ap-south-1.amazonaws.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 465
EMAIL_HOST_USER = 'AKIA3ZRX6OXO23ZOCYAY'
DEFAULT_FROM_EMAIL = 'AKIA3ZRX6OXO23ZOCYAY'
EMAIL_HOST_PASSWORD = 'BCyw3sVTk4OinHwnKKc4UtFwNqTY+UJYeY7xuvjFtF07'
# AUTH_USER_MODEL = 'users.User'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'smartlegal005@gmail.com'
# DEFAULT_FROM_EMAIL = 'smartlegal005@gmail.com'
# EMAIL_HOST_PASSWORD = 'Abcd@123'

#Flash Messaege settings
# MESSAGE_LEVEL = message_constants.DEBUG
MESSAGE_LEVEL = 10


from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# PAYTM DETAILS
HOST_URL = "https://www.vipnumbershop.com/"
PAYTM_CALLBACK_URL = "/paytm/response/"
PAGE_LIMIT = 10
if DEBUG:
    PAYTM_MERCHANT_ID = 'VIPNUM99688903292546'
    PAYTM_MERCHANT_KEY = '1ADG##wq1Wn!dF4i'
    PAYTM_WEBSITE = 'DEFAULT'
    HOST_URL = 'https://www.vipnumbershop.com/'
    INDUSTRY_TYPE = "Retail109"
    TRANSACTION_URL ='https://securegw.paytm.in/order/process'
    TRANSACTION_STATUS_URL = 'https://securegw.paytm.in/order/status'