# Generated by Django 3.1.7 on 2021-04-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Results'},
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='email',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_department', to='menu.riwazmenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='results',
            field=models.CharField(blank=True, max_length=4600),
        ),
    ]
