# Generated by Django 3.1.7 on 2021-04-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20210401_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='category_id',
        ),
    ]
